import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home(props) {
  const time = Date.now() - props.lastOutageEpoch;
  const delta = Math.floor(time / (24 * 60 * 60 * 1000))

  return (
    <div className={styles.container}>
      <Head>
        <title>Github Outage Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Days since last Github outage
        </h1>

        <p className={styles.description}>
          {delta}
        </p>
      </main>
    </div>
  )
}

export function getServerSideProps() {
  return {
    props: {
      lastOutageEpoch: parseInt(process.env.LAST_OUTAGE_EPOCH)
    }
  }
}
